apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bootcamp
spec:
  selector:
    matchLabels:
      app: k8s-bootcamp
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-bootcamp
    spec:
      containers:
      - name: k8s-bootcamp
        image: tiberna.azurecr.io/k8s-bootcamp:__imageTag__
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-bootcamp
spec:
  type: LoadBalancer
  selector:
    app: k8s-bootcamp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80